# Generated by Django 2.0 on 2019-05-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('departure_state', models.CharField(choices=[('LAG', 'Lagos'), ('ABJ', 'Abuja'), ('KAD', 'Kaduna'), ('JOS', 'Jos'), ('BEN', 'Benin'), ('SKT', 'Sokoto'), ('PHC', 'Portharcout'), ('ENU', 'enugu'), ('IBD', 'ibadan'), ('EDO', 'edo'), ('OGN', 'ogun'), ('DEL', 'delta'), ('CAL', 'calabar')], default='Choose a City', max_length=20)),
                ('arrival_state', models.CharField(choices=[('LAG', 'Lagos'), ('ABJ', 'Abuja'), ('KAD', 'Kaduna'), ('JOS', 'Jos'), ('BEN', 'Benin'), ('SKT', 'Sokoto'), ('PHC', 'Portharcout'), ('ENU', 'enugu'), ('IBD', 'ibadan'), ('EDO', 'edo'), ('OGN', 'ogun'), ('DEL', 'delta'), ('CAL', 'calabar')], default='Choose a City', max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('name', models.CharField(max_length=500)),
                ('transportation_line_logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transport_lines.TransportationLine'),
        ),
    ]
