# Generated by Django 2.0 on 2019-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport_lines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.AddField(
            model_name='transportationline',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
